# Generated by Django 3.0.5 on 2020-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nphone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
