# Generated by Django 3.0.5 on 2020-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_customer_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
