# Generated by Django 3.0.5 on 2020-04-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200424_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
