# Generated by Django 3.0.5 on 2020-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200426_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userpicture',
            new_name='user_picture',
        ),
    ]
