# Generated by Django 3.0.5 on 2020-04-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20200426_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_picture',
            new_name='userpicture',
        ),
    ]
