# Generated by Django 3.0.5 on 2020-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200426_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='userpicture',
            new_name='picture',
        ),
    ]
