# Generated by Django 3.0.5 on 2020-04-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customer_nphone'),
        ('Manager', '0002_auto_20200420_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Vendor'),
        ),
    ]
