# Generated by Django 3.0.5 on 2020-04-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customer_nphone'),
        ('Manager', '0003_restaurant_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Vendor'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='order_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Order_list'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, upload_to='menu_image'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Restaurant'),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Order'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, upload_to='restaurant_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Type'),
        ),
    ]
