# Generated by Django 3.0.5 on 2020-04-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20200423_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='order_list',
        ),
        migrations.AddField(
            model_name='order_list',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Menu'),
        ),
    ]
