# Generated by Django 3.0.5 on 2020-04-24 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200423_1355'),
        ('Manager', '0005_auto_20200423_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Customer'),
        ),
    ]
