# Generated by Django 3.0.5 on 2020-04-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/menu_image'),
        ),
    ]
