# Generated by Django 3.0.5 on 2020-04-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_auto_20200424_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='type_id',
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Menu'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('ร้านอาหาร', 'food'), ('ร้านเครื่องดื่ม', 'drink')], default='ร้านอาหาร', max_length=15),
        ),
        migrations.DeleteModel(
            name='Order_list',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
