# Generated by Django 3.0.5 on 2020-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0010_auto_20200425_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('เสร็จแล้ว', 'success'), ('กำลังทำ', 'inprogress')], default='กำลังทำ', max_length=15),
        ),
    ]
